[Regridding]
# Target Ice Sheet (AIS or GrIS)
icesheet = AIS
#Target resolution (m) AIS = 2000, GrIS = 1000
target_res = 2000
# Paths to geometry and weights
weights_file = /projects/grid/ghub/ISMIP6/devon/grid/AIS/weights/AIS_SDBN_2km_weights.nc
num_workers = 24
regrid_scheme = conservative

[Source]
# Source information
src_dir = /projects/grid/ghub/ISMIP7/prep/AIS/CESM2-WACCM/historical/SDBN1_raw/v1/
#Should be a 4 digit epsg code. TODO: add functionality for "curvilinear"
#AIS = 3031, GrIS = 3413
src_epsg = 3031
gcm = CESM2-WACCM
scenario = historical
method = SDBN1

[Output]
# Output information
output_dir = /projects/grid/ghub/ISMIP6/devon/ISMIP_regridding/OUTPUT/
scratch_dir = /vscratch/grp-ghub/devon-temp/temp/
var_list = tas
version = 1

[Cases]
#booleans to compute gradients, climatology, and anomalies
#yes or no to regrid the output files
normal = yes
#yes or no to regrid the gradient files
gradients = no




