[Regridding]
# Target Ice Sheet (AIS or GrIS)
icesheet = AIS
#Target resolution (m) AIS = 2000, GrIS = 1000
target_res = 2000
# Paths to geometry and weights
weights_dir = weights/
masks_dir = masks/
num_workers = 12
regrid_scheme = conservative

[Source]
# Source information
src_dir = /projects/grid/ghub/ISMIP7/prep/AIS/OCX/SDBN1_raw/
gcm = RACMO2.3p2_ERA
scenario = OCX
method = SDBN1-2000m

[Output]
# Output information
output_dir = /vscratch/grp-ghub/devon-temp/OUTPUT-test/
scratch_dir = /vscratch/grp-ghub/devon-temp/temp/
var_list = acabf, pr, mrro, tas, ts
version = 1

[Gradients]
gradients_var_list = acabf, mrro, tas, ts

[Cases]
#booleans to compute gradients, climatology, and anomalies
#yes or no to regrid the output files
regrid = yes
#yes or no to compute climatology
climatology = no
#yes or no to compute anomalies
anomalies = no
#yes or no to regrid the gradient files
gradients = no




