[Regridding]
# Target Ice Sheet (AIS or GrIS)
icesheet = AIS
#Target resolution (m) AIS = 2000, GrIS = 1000
target_res = 8000
# Paths to geometry and weights
weights_dir = weights/
masks_dir = masks/
num_workers = 24
regrid_scheme = conservative

[Source]
# Source information
src_dir = /projects/grid/ghub/ISMIP7/prep/AIS/CESM2-WACCM/historical/SDBN1_raw/v2/
gcm = CESM2-WACCM
scenario = historical
method = SDBN1-8000m

[Output]
# Output information
output_dir = /vscratch/grp-ghub/devon-temp/OUTPUT/
scratch_dir = /vscratch/grp-ghub/devon-temp/temp/
var_list = pr, mrro, tas, ts
version = 2

[Gradients]
gradients_var_list = acabf, mrro, ts

[Cases]
#booleans to compute gradients, climatology, and anomalies
#yes or no to regrid the output files
regrid = yes
#yes or no to regrid the output files
climatology = yes
#yes or no to regrid the output files
anomalies = yes
#yes or no to regrid the gradient files
gradients = yes




